name: macOS

on:
  push:
    tags:
      - "*"

jobs:
  build-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: "qtcharts"

      - name: Install dependencies
        run: |
          brew install boost

      - name: Clone conceal-core
        run: |
          rm -rf cryptonote
          git clone https://github.com/ConcealNetwork/conceal-core.git cryptonote

      - name: Build
        id: build
        run: |
          build_folder="build/release"
          ccx_version=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
          release_name="ccx-desktop-macOS-v$ccx_version"
          app_name="conceal-desktop.app"

          make -j4 build-release
          cd "$build_folder"
          macdeployqt "$app_name"
          cpack
          mkdir "$release_name"
          mv *.dmg "$release_name".dmg
          zip "$release_name".zip "$release_name".dmg
          sha256=$(shasum -a 256 "$release_name".zip | awk '{ print toupper($1) }')

          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.zip"
          echo "::set-output name=asset_path::$build_folder/$release_name.zip"
          echo "::set-output name=ccx_version::${ccx_version}"

      # since https://github.com/softprops/action-gh-release/pull/145 body is replaced instead of being appended
      # use v0.1.12 for now
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.12
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Conceal Desktop v${{ steps.build.outputs.ccx_version }}
          body: |
            [Download for macOS](../../releases/download/${{ steps.build.outputs.ccx_version }}/${{ steps.build.outputs.release_name }}) **${{ steps.build.outputs.release_name }}**
            `SHA256 : ${{ steps.build.outputs.sha256 }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
