name: Ubuntu 16.04

on:
  push:
    tags:
      - "*"

jobs:
  build-ubuntu16:
    name: Ubuntu 16.04
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y qt5-default qttools5-dev qttools5-dev-tools libboost-all-dev

      - name: Clone conceal-core
        run: |
          rm -rf cryptonote
          git clone https://github.com/ConcealNetwork/conceal-core.git cryptonote

      - name: Build
        id: build
        run: |
          ccx_version=$(echo "$GITHUB_REF" | sed 's|refs/tags/||')
          release_name=ccx-desktop-ubuntu-1604-v"$ccx_version"
          build_folder="build/release"

          make -j4 build-release
          mkdir $release_name
          mkdir -p $release_name/icon
          mv $build_folder/CONCEAL-GUI $release_name
          cp conceal-desktop.desktop $release_name
          cp src/images/conceal.png $release_name/icon
          tar -czf "$release_name".tar.gz "$release_name"
          sha256=$(shasum -a 256 "$release_name".tar.gz | awk '{print toupper($1)}')

          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.tar.gz"
          echo "::set-output name=ccx_version::${ccx_version}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.release_name }}
          name: Conceal Desktop v${{ steps.build.outputs.ccx_version }}
          body: |
            <img src="https://image.flaticon.com/icons/svg/25/25719.svg" width="16"> [Download for Ubuntu 16.04](../../releases/download/${{ steps.build.outputs.ccx_version }}/${{ steps.build.outputs.release_name }}) **${{ steps.build.outputs.release_name }}**
            `SHA256 : ${{ steps.build.outputs.sha256 }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
